# Generated by Django 2.1.7 on 2019-03-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myquotes',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
